---
ID: "a342c8eb-7b17-4d4f-b3f5-3fb742c808ca"
Parent: "62f64df8-74f0-4cf3-911f-7a614269e971"
Template: "85c25516-a362-4633-97cd-2411548bd09b"
Path: /sitecore/content/SitecoreCoffee/Settings
DB: master
SharedFields:
- ID: "fd50ea84-6fff-4de8-a38f-47e2ab0673b9"
  Hint: MaintenanceModeOn
  Type: Checkbox
  Value: 0
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20180308T141049Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\admin
    - ID: "fd50ea84-6fff-4de8-a38f-47e2ab0673b9"
      Hint: MaintenanceModeOn
      Type: Checkbox
      Value: 1
